### PR TITLE
Support chemical JSON

### PR DESCRIPTION
**Pull request by awvwgk**
Enable support for reading chemical JSON in `xtb`, `dftd4`, etc., chemical JSON is beside CML the only format supported in Avogadro 2 for saving structures.

- [x] implement basic reader for chemical JSON
- [x] implement writer for chemical JSON
- [x] test if chemical JSON produced by mctc-lib round-trips
- [x] document implemented format

Specs:
- https://wiki.openchemistry.org/Chemical_JSON (updated 2017!)
- https://github.com/OpenChemistry/chemicaljson/blob/master/chemicaljson.md (updated 2019!)
- https://github.com/OpenChemistry/chemicaljson/issues/15

Impl.:
- https://github.com/OpenChemistry/avogadrolibs/blob/master/avogadro/io/cjsonformat.cpp
  (not a formal spec, different from specs...)

### CODE REVIEW

**Comment by awvwgk** [comment]
@ghutchis Is there a more up-to-date specification of chemical JSON than https://wiki.openchemistry.org/Chemical_JSON?

**Comment by ghutchis** [comment]
I don't know, for example, if anything "in the wild" only prints the lattice parameters. For a while now, Avogadro writes the lattice vectors, e.g.

[KBr.txt](https://github.com/grimme-lab/mctc-lib/files/9191922/KBr.txt)

Happy to continue the discussion. I'm building up the interactive optimization and several people (including myself) would like to use `xtb` methods. Being able to write `cjson` instead of Turbomole coords would be nice, although I implemented that recently.

On the writer side, there's a lot that can be supported or improved. Happy to continue the conversation - probably better on the chemicaljson repository.

**Comment by awvwgk** [comment]
I think I got the format implemented now. Avogadro 2 happily reads the cjson files I'm producing.

**Comment by matterhorn103** [comment]
Sure, sorry! Still getting used to the structure of open source projects e.g. that docs are typically in a separate repo

**Pull request merged**
